import { CardWithTapLimit, CardWithCoinsPerHour } from "./types";

export const SimpleList: CardWithTapLimit[] = [
  {
    name: "Custodian Wallet",
    level: 3,
    tapLimit: 300,
    extraTapLimit: 100,
    upgradeCost: 850,
  },
  {
    name: "CEX",
    level: 10,
    tapLimit: 1500,
    extraTapLimit: 150,
    upgradeCost: 4800,
  },
  {
    name: "Spot Trading",
    level: 2,
    tapLimit: 600,
    extraTapLimit: 300,
    upgradeCost: 1650,
  },
  {
    name: "P2P",
    level: 1,
    tapLimit: 200,
    extraTapLimit: 200,
    upgradeCost: 950,
  },
  {
    name: "Margin Trading",
    level: 3,
    tapLimit: 900,
    extraTapLimit: 300,
    upgradeCost: 2950,
  },
  {
    name: "Referrals Programs",
    level: 1,
    tapLimit: 250,
    extraTapLimit: 250,
    upgradeCost: 950,
  },
].map((card) => ({ ...card, listType: "Simple", gainType: "tap_limit" }));

export const CoinsList: CardWithCoinsPerHour[] = [
  {
    name: "Blockchain",
    level: 5,
    coinsPerHour: 10,
    extraCoinsPerHour: 2,
    upgradeCost: 335,
  },
  {
    name: "Bitcoin",
    level: 6,
    coinsPerHour: 18,
    extraCoinsPerHour: 3,
    upgradeCost: 335,
  },
  {
    name: "Stablecoins",
    level: 1,
    coinsPerHour: 2,
    extraCoinsPerHour: 2,
    upgradeCost: 80,
  },
  {
    name: "Ethereum",
    level: 5,
    coinsPerHour: 12.5,
    extraCoinsPerHour: 2.5,
    upgradeCost: 80,
  },
  {
    name: "Ripple",
    level: 1,
    coinsPerHour: 11,
    extraCoinsPerHour: 11,
    upgradeCost: 220,
  },
  {
    name: "Cardano",
    level: 1,
    coinsPerHour: 13,
    extraCoinsPerHour: 13,
    upgradeCost: 320,
  },
  {
    name: "Polkadot",
    level: 1,
    coinsPerHour: 14,
    extraCoinsPerHour: 14,
    upgradeCost: 330,
  },
  {
    name: "Litecoin",
    level: 1,
    coinsPerHour: 10,
    extraCoinsPerHour: 10,
    upgradeCost: 170,
  },
  {
    name: "Bitcoin Cash",
    level: 1,
    coinsPerHour: 12,
    extraCoinsPerHour: 12,
    upgradeCost: 310,
  },
  {
    name: "Binance Smart Chain",
    level: 1,
    coinsPerHour: 10,
    extraCoinsPerHour: 10,
    upgradeCost: 190,
  },
  {
    name: "Stellar",
    level: 1,
    coinsPerHour: 15,
    extraCoinsPerHour: 15,
    upgradeCost: 340,
  },
  {
    name: "Solana",
    level: 1,
    coinsPerHour: 16,
    extraCoinsPerHour: 16,
    upgradeCost: 360,
  },
  {
    name: "Avalance",
    level: 1,
    coinsPerHour: 16,
    extraCoinsPerHour: 16,
    upgradeCost: 320,
  },
  {
    name: "Tron",
    level: 1,
    coinsPerHour: 20,
    extraCoinsPerHour: 20,
    upgradeCost: 450,
  },
  {
    name: "Cosmos",
    level: 1,
    coinsPerHour: 18,
    extraCoinsPerHour: 18,
    upgradeCost: 350,
  },
  {
    name: "TON",
    level: 1,
    coinsPerHour: 30,
    extraCoinsPerHour: 30,
    upgradeCost: 630,
  },
].map((card) => ({ ...card, listType: "Coins", gainType: "coins_per_hour" }));

export const InvestList: CardWithCoinsPerHour[] = [
  {
    name: "Crypto Mining",
    level: 15,
    coinsPerHour: 30,
    extraCoinsPerHour: 2,
    upgradeCost: 4350,
  },
  {
    name: "Earn",
    level: 10,
    coinsPerHour: 50,
    extraCoinsPerHour: 5,
    upgradeCost: 3530,
  },
  {
    name: "Staking",
    level: 1,
    coinsPerHour: 20,
    extraCoinsPerHour: 20,
    upgradeCost: 500,
  },
  {
    name: "Yield Farming",
    level: 1,
    coinsPerHour: 25,
    extraCoinsPerHour: 25,
    upgradeCost: 590,
  },
  {
    name: "Lending",
    level: 1,
    coinsPerHour: 28,
    extraCoinsPerHour: 28,
    upgradeCost: 660,
  },
  {
    name: "Liquidity Mining",
    level: 1,
    coinsPerHour: 40,
    extraCoinsPerHour: 40,
    upgradeCost: 960,
  },
  // {
  //   name: "Non-Fungible Tokens",
  //   level: 1,
  //   coinsPerHour: 50,
  //   extraCoinsPerHour: 50,
  //   upgradeCost: 1,
  // }
].map((card) => ({ ...card, listType: "Invest", gainType: "coins_per_hour" }));

export const AcademyList: CardWithTapLimit[] = [
  {
    name: "Non-custodian wallet",
    level: 1,
    tapLimit: 100,
    extraTapLimit: 100,
    upgradeCost: 500,
  },
  {
    name: "DEX",
    level: 10,
    tapLimit: 1000,
    extraTapLimit: 100,
    upgradeCost: 2300,
  },
  {
    name: "DEX Swaps",
    level: 1,
    tapLimit: 200,
    extraTapLimit: 200,
    upgradeCost: 750,
  },
  {
    name: "Crypto Sectors",
    level: 10,
    tapLimit: 2000,
    extraTapLimit: 200,
    upgradeCost: 9600,
  },
  {
    name: "PoW",
    level: 2,
    tapLimit: 600,
    extraTapLimit: 300,
    upgradeCost: 1650,
  },
  {
    name: "Layer 1 / Layer 2",
    level: 1,
    tapLimit: 300,
    extraTapLimit: 300,
    upgradeCost: 1100,
  },
  {
    name: "DeFi",
    level: 1,
    tapLimit: 300,
    extraTapLimit: 300,
    upgradeCost: 1200,
  },
  {
    name: "Infrastructure",
    level: 5,
    tapLimit: 2000,
    extraTapLimit: 400,
    upgradeCost: 12450,
  },
  {
    name: "AI",
    level: 2,
    tapLimit: 800,
    extraTapLimit: 400,
    upgradeCost: 2500,
  },
  {
    name: "Meta",
    level: 2,
    tapLimit: 800,
    extraTapLimit: 400,
    upgradeCost: 2550,
  },
  {
    name: "Games",
    level: 5,
    tapLimit: 2000,
    extraTapLimit: 400,
    upgradeCost: 13750,
  },
  {
    name: "Fan",
    level: 1,
    tapLimit: 500,
    extraTapLimit: 500,
    upgradeCost: 1800,
  },
  {
    name: "NFT",
    level: 3,
    tapLimit: 1500,
    extraTapLimit: 500,
    upgradeCost: 7750,
  },
  {
    name: "Data Storage",
    level: 1,
    tapLimit: 500,
    extraTapLimit: 500,
    upgradeCost: 2000,
  },
  // {
  //   name: "Mems",
  //   level: 1,
  //   tapLimit: 500,
  //   extraTapLimit: 500,
  //   upgradeCost: 1,
  // }
].map((card) => ({
  ...card,
  listType: "Academy",
  gainType: "tap_limit",
}));
